spring.application.name=Donation-platform

spring.datasource.url=jdbc:postgresql://dpg-d7o5dgrbc2fs7396vgig-a:5432/donation_db_nrcq?sslmode=require
spring.datasource.username=donation_db_nrcq_user
spring.datasource.password=itxQ7CfyLt6UZ7NM7ry7TXRVEjnjkfLk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080